# SPDX-FileCopyrightText: 2023 Mario Franke <research@m-franke.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later

jobs: all
printshellcmds: True
use-singularity: True
singularity-args: "-H ../../:/space_veins -C --network none"
# slurm: True
# default-resources:
#   - mem_mb_per_cpu=4000
#   - tasks=6